name: Continuous Integration
  
on: 
  pull_request:
    branches:
      - master
  
jobs:
  test:
    runs-on: ubuntu-latest
  
    container: node:14-bullseye

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
  
    steps:
    - uses: actions/checkout@v2
    - name: npm install migrate and test
      run: |
        npm install
        npm run migrate up
        npm run test
      env:
        CI: true
        PGHOST_TEST: postgres # using container, no need to save on secrets
        PGUSER_TEST: postgres
        PGDATABASE_TEST: postgres
        PGPASSWORD_TEST: postgres
        PGPORT_TEST: 5432
        PGHOST: postgres
        PGUSER: postgres
        PGDATABASE: postgres
        PGPASSWORD: postgres
        PGPORT: 5432
        ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
        REFRESH_TOKEN_KEY: ${{ secrets.REFRESH_TOKEN_KEY }}
        ACCESS_TOKEN_AGE: 1000
